DROP TABLE IF EXISTS ENTRIES;
--DROP TABLE IF EXISTS PHONEBOOK;

--CREATE TABLE PHONEBOOK (
--    ID INT AUTO_INCREMENT,
--    NAME VARCHAR(250),
--    PRIMARY KEY (ID)
--
--);

CREATE TABLE ENTRIES (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(250) NOT NULL,
    SURNAME VARCHAR(250) NOT NULL,
    NUMBER VARCHAR(250),
    --PHONEBOOK_ID INT,
    PRIMARY KEY (ID),
    --FOREIGN KEY(PHONEBOOK_ID) REFERENCES PHONEBOOK (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

--INSERT INTO PHONEBOOK (ID, NAME) VALUES (1, 'ABSA');
INSERT INTO ENTRIES(ID, NAME, SURNAME, NUMBER) values (1, 'SONWABILE', 'NOMNGANGA', '0733997671');